#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# regex to validate in commit msg
#error_msg="Aborting commit. Your commit message is missing either a Jira Issue ('[KO-111] add new feature')"
#commit_message=$(cat "$1")
#
#check_message_format() {
#  local REGEX='(^\[(KOCCC)|(CEPSUPPORT)\-[0-9]+\] |merge|chore\(pkg\-|Revert|\[REFACTOR\]|\[TECH\]|\[FIX\]|\[FEAT\])'
#  if [[ ! $commit_message =~ $REGEX ]]; then
#    echo >&2 $error_msg
#    exit 1
#  fi
#}
#
#check_message_format
